package manifest

import "encoding/json"

type Icon struct {
	Source string `json:"src"`
	Sizes string `json:"sizes"`
	Type string `json:"type,omitempty"`
}

type Manifest struct {
	Name string 			`json:"name"`
	ShortName string 		`json:"short_name"`
	StartUrl string 		`json:"start_url"`
	Display string			`json:"display"`
	BackgroundColor string 	`json:"background_color"`
	Description string 		`json:"description"`
	ThemeColor string		`json:"theme_color"`
	
	Icons []Icon			`json:"icons"`
}

func New() Manifest {
	var manifest Manifest
	manifest.StartUrl = "/"
	manifest.Display = "standalone"
	manifest.BackgroundColor = "#fff"
	return manifest
}

func (manifest Manifest) Render() []byte {
	var result, _ = json.Marshal(manifest)
	return result
}

// Set the name of this application.
func (manifest *Manifest) SetName(name string) {
	manifest.Name = name
	if manifest.ShortName == "" {
		manifest.ShortName = name
	}
}

// Set the short name of the application generated by this seed.
func (manifest *Manifest) SetShortName(name string) {
	manifest.ShortName = name
}


// Set the description of the application generated by this seed.
func (manifest *Manifest) SetDescription(description string) {
	manifest.Description = description
}

// Set the icon for the application generated by this seed.
func (manifest *Manifest) SetIcon(path string) {
	var icon Icon
	icon.Source = path
	icon.Sizes = "192x192"

	manifest.Icons = append(manifest.Icons, icon)
}

func (manifest *Manifest) SetThemeColor(color string) {
	//TODO use color.Color
	manifest.ThemeColor = color
}